title: Xiyao Chen's Homepage
page-top-title: Xiyao Chen
top-section-bg-text: Personal Website
home-subtitle: Xiyao Chen&ensp;|&ensp;陈西尧
copyright-text: '&copy; Xiyao Chen 2023-2026. All Rights Reserved.'
